"""add receipt category

Revision ID: 56720fc99c3d
Revises: 94cc6a81e6c6
Create Date: 2026-02-04 14:10:35.489200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56720fc99c3d'
down_revision: Union[str, Sequence[str], None] = '94cc6a81e6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('category', sa.String(length=32), server_default='OTHER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'category')
    # ### end Alembic commands ###
