"""add detected_currency

Revision ID: 94cc6a81e6c6
Revises: 821fa5c8078d
Create Date: 2026-02-04 13:00:15.669416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94cc6a81e6c6'
down_revision: Union[str, Sequence[str], None] = '821fa5c8078d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('detected_currency', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'detected_currency')
    # ### end Alembic commands ###
