"""add usd totals

Revision ID: d19df252f96f
Revises: 8065818fbd3f
Create Date: 2026-02-04 03:39:40.308627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19df252f96f'
down_revision: Union[str, Sequence[str], None] = '8065818fbd3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_items', sa.Column('line_total_usd', sa.Float(), nullable=True))
    op.add_column('receipts', sa.Column('total_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'total_usd')
    op.drop_column('receipt_items', 'line_total_usd')
    # ### end Alembic commands ###
